import os
import numpy as np
import tempfile, zipfile
import torch
import torch.nn as nn
import torch.nn.functional as F
try:
    import torchvision
except:
    pass

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        self.1_backbone_0_inception_0_bottleneck_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=1, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_0_convs_0_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(39,), out_channels=32, padding=(19,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_0_convs_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(19,), out_channels=32, padding=(9,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_0_convs_2_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(9,), out_channels=32, padding=(4,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_0_mp_conv_0 = nn.MaxPool1d(ceil_mode=False, dilation=(1,), kernel_size=(3,), padding=(1,), return_indices=False, stride=(1,))
        self.1_backbone_0_inception_0_mp_conv_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=1, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_0_norm = nn.BatchNorm1d(affine=True, eps=0.000010, num_features=128)
        self.1_backbone_0_inception_0_act = nn.ReLU()
        self.1_backbone_0_inception_1_bottleneck_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_1_convs_0_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(39,), out_channels=32, padding=(19,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_1_convs_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(19,), out_channels=32, padding=(9,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_1_convs_2_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(9,), out_channels=32, padding=(4,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_1_mp_conv_0 = nn.MaxPool1d(ceil_mode=False, dilation=(1,), kernel_size=(3,), padding=(1,), return_indices=False, stride=(1,))
        self.1_backbone_0_inception_1_mp_conv_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_1_norm = nn.BatchNorm1d(affine=True, eps=0.000010, num_features=128)
        self.1_backbone_0_inception_1_act = nn.ReLU()
        self.1_backbone_0_inception_2_bottleneck_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_2_convs_0_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(39,), out_channels=32, padding=(19,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_2_convs_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(19,), out_channels=32, padding=(9,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_2_convs_2_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(9,), out_channels=32, padding=(4,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_2_mp_conv_0 = nn.MaxPool1d(ceil_mode=False, dilation=(1,), kernel_size=(3,), padding=(1,), return_indices=False, stride=(1,))
        self.1_backbone_0_inception_2_mp_conv_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_2_norm = nn.BatchNorm1d(affine=True, eps=0.000010, num_features=128)
        self.convbn1d_0 = nn.Conv1d(bias=True, dilation=(1,), groups=1, in_channels=1, kernel_size=(1,), out_channels=128, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_act_0 = nn.ReLU()
        self.1_backbone_0_inception_3_bottleneck_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_3_convs_0_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(39,), out_channels=32, padding=(19,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_3_convs_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(19,), out_channels=32, padding=(9,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_3_convs_2_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(9,), out_channels=32, padding=(4,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_3_mp_conv_0 = nn.MaxPool1d(ceil_mode=False, dilation=(1,), kernel_size=(3,), padding=(1,), return_indices=False, stride=(1,))
        self.1_backbone_0_inception_3_mp_conv_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_3_norm = nn.BatchNorm1d(affine=True, eps=0.000010, num_features=128)
        self.1_backbone_0_inception_3_act = nn.ReLU()
        self.1_backbone_0_inception_4_bottleneck_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_4_convs_0_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(39,), out_channels=32, padding=(19,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_4_convs_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(19,), out_channels=32, padding=(9,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_4_convs_2_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(9,), out_channels=32, padding=(4,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_4_mp_conv_0 = nn.MaxPool1d(ceil_mode=False, dilation=(1,), kernel_size=(3,), padding=(1,), return_indices=False, stride=(1,))
        self.1_backbone_0_inception_4_mp_conv_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_4_norm = nn.BatchNorm1d(affine=True, eps=0.000010, num_features=128)
        self.1_backbone_0_inception_4_act = nn.ReLU()
        self.1_backbone_0_inception_5_bottleneck_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_5_convs_0_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(39,), out_channels=32, padding=(19,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_5_convs_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(19,), out_channels=32, padding=(9,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_5_convs_2_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=32, kernel_size=(9,), out_channels=32, padding=(4,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_5_mp_conv_0 = nn.MaxPool1d(ceil_mode=False, dilation=(1,), kernel_size=(3,), padding=(1,), return_indices=False, stride=(1,))
        self.1_backbone_0_inception_5_mp_conv_1_0 = nn.Conv1d(bias=False, dilation=(1,), groups=1, in_channels=128, kernel_size=(1,), out_channels=32, padding=(0,), padding_mode='zeros', stride=(1,))
        self.1_backbone_0_inception_5_norm = nn.BatchNorm1d(affine=True, eps=0.000010, num_features=128)
        self.1_backbone_0_shortcut_1 = nn.BatchNorm1d(affine=True, eps=0.000010, num_features=128)
        self.1_backbone_0_act_1 = nn.ReLU()
        self.1_head_0_0_gap = nn.AdaptiveAvgPool1d(output_size=(1,))
        self.1_head_0_1_0 = nn.Linear(bias=True, in_features=128, out_features=3)
        self.2 = nn.Softmax(dim=1)

        archive = zipfile.ZipFile('../../../../../../../models/traced_model.pnnx.bin', 'r')
        self.1_backbone_0_inception_0_bottleneck_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.0.bottleneck.0.weight', (32,1,1), 'float32')
        self.1_backbone_0_inception_0_convs_0_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.0.convs.0.0.weight', (32,32,39), 'float32')
        self.1_backbone_0_inception_0_convs_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.0.convs.1.0.weight', (32,32,19), 'float32')
        self.1_backbone_0_inception_0_convs_2_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.0.convs.2.0.weight', (32,32,9), 'float32')
        self.1_backbone_0_inception_0_mp_conv_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.0.mp_conv.1.0.weight', (32,1,1), 'float32')
        self.1_backbone_0_inception_0_norm.bias = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.0.norm.bias', (128), 'float32')
        self.1_backbone_0_inception_0_norm.running_mean = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.0.norm.running_mean', (128), 'float32')
        self.1_backbone_0_inception_0_norm.running_var = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.0.norm.running_var', (128), 'float32')
        self.1_backbone_0_inception_0_norm.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.0.norm.weight', (128), 'float32')
        self.1_backbone_0_inception_1_bottleneck_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.1.bottleneck.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_1_convs_0_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.1.convs.0.0.weight', (32,32,39), 'float32')
        self.1_backbone_0_inception_1_convs_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.1.convs.1.0.weight', (32,32,19), 'float32')
        self.1_backbone_0_inception_1_convs_2_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.1.convs.2.0.weight', (32,32,9), 'float32')
        self.1_backbone_0_inception_1_mp_conv_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.1.mp_conv.1.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_1_norm.bias = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.1.norm.bias', (128), 'float32')
        self.1_backbone_0_inception_1_norm.running_mean = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.1.norm.running_mean', (128), 'float32')
        self.1_backbone_0_inception_1_norm.running_var = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.1.norm.running_var', (128), 'float32')
        self.1_backbone_0_inception_1_norm.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.1.norm.weight', (128), 'float32')
        self.1_backbone_0_inception_2_bottleneck_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.2.bottleneck.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_2_convs_0_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.2.convs.0.0.weight', (32,32,39), 'float32')
        self.1_backbone_0_inception_2_convs_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.2.convs.1.0.weight', (32,32,19), 'float32')
        self.1_backbone_0_inception_2_convs_2_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.2.convs.2.0.weight', (32,32,9), 'float32')
        self.1_backbone_0_inception_2_mp_conv_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.2.mp_conv.1.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_2_norm.bias = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.2.norm.bias', (128), 'float32')
        self.1_backbone_0_inception_2_norm.running_mean = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.2.norm.running_mean', (128), 'float32')
        self.1_backbone_0_inception_2_norm.running_var = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.2.norm.running_var', (128), 'float32')
        self.1_backbone_0_inception_2_norm.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.2.norm.weight', (128), 'float32')
        self.convbn1d_0.bias = self.load_pnnx_bin_as_parameter(archive, 'convbn1d_0.bias', (128), 'float32')
        self.convbn1d_0.weight = self.load_pnnx_bin_as_parameter(archive, 'convbn1d_0.weight', (128,1,1), 'float32')
        self.1_backbone_0_inception_3_bottleneck_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.3.bottleneck.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_3_convs_0_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.3.convs.0.0.weight', (32,32,39), 'float32')
        self.1_backbone_0_inception_3_convs_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.3.convs.1.0.weight', (32,32,19), 'float32')
        self.1_backbone_0_inception_3_convs_2_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.3.convs.2.0.weight', (32,32,9), 'float32')
        self.1_backbone_0_inception_3_mp_conv_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.3.mp_conv.1.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_3_norm.bias = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.3.norm.bias', (128), 'float32')
        self.1_backbone_0_inception_3_norm.running_mean = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.3.norm.running_mean', (128), 'float32')
        self.1_backbone_0_inception_3_norm.running_var = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.3.norm.running_var', (128), 'float32')
        self.1_backbone_0_inception_3_norm.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.3.norm.weight', (128), 'float32')
        self.1_backbone_0_inception_4_bottleneck_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.4.bottleneck.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_4_convs_0_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.4.convs.0.0.weight', (32,32,39), 'float32')
        self.1_backbone_0_inception_4_convs_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.4.convs.1.0.weight', (32,32,19), 'float32')
        self.1_backbone_0_inception_4_convs_2_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.4.convs.2.0.weight', (32,32,9), 'float32')
        self.1_backbone_0_inception_4_mp_conv_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.4.mp_conv.1.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_4_norm.bias = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.4.norm.bias', (128), 'float32')
        self.1_backbone_0_inception_4_norm.running_mean = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.4.norm.running_mean', (128), 'float32')
        self.1_backbone_0_inception_4_norm.running_var = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.4.norm.running_var', (128), 'float32')
        self.1_backbone_0_inception_4_norm.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.4.norm.weight', (128), 'float32')
        self.1_backbone_0_inception_5_bottleneck_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.5.bottleneck.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_5_convs_0_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.5.convs.0.0.weight', (32,32,39), 'float32')
        self.1_backbone_0_inception_5_convs_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.5.convs.1.0.weight', (32,32,19), 'float32')
        self.1_backbone_0_inception_5_convs_2_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.5.convs.2.0.weight', (32,32,9), 'float32')
        self.1_backbone_0_inception_5_mp_conv_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.5.mp_conv.1.0.weight', (32,128,1), 'float32')
        self.1_backbone_0_inception_5_norm.bias = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.5.norm.bias', (128), 'float32')
        self.1_backbone_0_inception_5_norm.running_mean = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.5.norm.running_mean', (128), 'float32')
        self.1_backbone_0_inception_5_norm.running_var = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.inception.5.norm.running_var', (128), 'float32')
        self.1_backbone_0_inception_5_norm.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.inception.5.norm.weight', (128), 'float32')
        self.1_backbone_0_shortcut_1.bias = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.shortcut.1.bias', (128), 'float32')
        self.1_backbone_0_shortcut_1.running_mean = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.shortcut.1.running_mean', (128), 'float32')
        self.1_backbone_0_shortcut_1.running_var = self.load_pnnx_bin_as_tensor(archive, '1.backbone.0.shortcut.1.running_var', (128), 'float32')
        self.1_backbone_0_shortcut_1.weight = self.load_pnnx_bin_as_parameter(archive, '1.backbone.0.shortcut.1.weight', (128), 'float32')
        self.1_head_0_1_0.bias = self.load_pnnx_bin_as_parameter(archive, '1.head.0.1.0.bias', (3), 'float32')
        self.1_head_0_1_0.weight = self.load_pnnx_bin_as_parameter(archive, '1.head.0.1.0.weight', (3,128), 'float32')
        archive.close()

    def load_pnnx_bin_as_parameter(self, archive, key, shape, dtype, requires_grad=True):
        return nn.Parameter(self.load_pnnx_bin_as_tensor(archive, key, shape, dtype), requires_grad)

    def load_pnnx_bin_as_tensor(self, archive, key, shape, dtype):
        fd, tmppath = tempfile.mkstemp()
        with os.fdopen(fd, 'wb') as tmpf, archive.open(key) as keyfile:
            tmpf.write(keyfile.read())
        m = np.memmap(tmppath, dtype=dtype, mode='r', shape=shape).copy()
        os.remove(tmppath)
        return torch.from_numpy(m)

    def forward(self, v_0):
        v_1 = torch.clone(input=v_0)
        v_2 = ((v_1 - -2.361164e+01) / 8.254822e+02)
        v_3 = self.1_backbone_0_inception_0_bottleneck_0(v_2)
        v_4 = self.1_backbone_0_inception_0_convs_0_0(v_3)
        v_5 = self.1_backbone_0_inception_0_convs_1_0(v_3)
        v_6 = self.1_backbone_0_inception_0_convs_2_0(v_3)
        v_7 = self.1_backbone_0_inception_0_mp_conv_0(v_2)
        v_8 = self.1_backbone_0_inception_0_mp_conv_1_0(v_7)
        v_9 = torch.cat((v_4, v_5, v_6, v_8), dim=1)
        v_10 = self.1_backbone_0_inception_0_norm(v_9)
        v_11 = self.1_backbone_0_inception_0_act(v_10)
        v_12 = self.1_backbone_0_inception_1_bottleneck_0(v_11)
        v_13 = self.1_backbone_0_inception_1_convs_0_0(v_12)
        v_14 = self.1_backbone_0_inception_1_convs_1_0(v_12)
        v_15 = self.1_backbone_0_inception_1_convs_2_0(v_12)
        v_16 = self.1_backbone_0_inception_1_mp_conv_0(v_11)
        v_17 = self.1_backbone_0_inception_1_mp_conv_1_0(v_16)
        v_18 = torch.cat((v_13, v_14, v_15, v_17), dim=1)
        v_19 = self.1_backbone_0_inception_1_norm(v_18)
        v_20 = self.1_backbone_0_inception_1_act(v_19)
        v_21 = self.1_backbone_0_inception_2_bottleneck_0(v_20)
        v_22 = self.1_backbone_0_inception_2_convs_0_0(v_21)
        v_23 = self.1_backbone_0_inception_2_convs_1_0(v_21)
        v_24 = self.1_backbone_0_inception_2_convs_2_0(v_21)
        v_25 = self.1_backbone_0_inception_2_mp_conv_0(v_20)
        v_26 = self.1_backbone_0_inception_2_mp_conv_1_0(v_25)
        v_27 = torch.cat((v_22, v_23, v_24, v_26), dim=1)
        v_28 = self.1_backbone_0_inception_2_norm(v_27)
        v_29 = self.convbn1d_0(v_2)
        v_30 = (v_28 + v_29)
        v_31 = self.1_backbone_0_act_0(v_30)
        v_32 = self.1_backbone_0_inception_3_bottleneck_0(v_31)
        v_33 = self.1_backbone_0_inception_3_convs_0_0(v_32)
        v_34 = self.1_backbone_0_inception_3_convs_1_0(v_32)
        v_35 = self.1_backbone_0_inception_3_convs_2_0(v_32)
        v_36 = self.1_backbone_0_inception_3_mp_conv_0(v_31)
        v_37 = self.1_backbone_0_inception_3_mp_conv_1_0(v_36)
        v_38 = torch.cat((v_33, v_34, v_35, v_37), dim=1)
        v_39 = self.1_backbone_0_inception_3_norm(v_38)
        v_40 = self.1_backbone_0_inception_3_act(v_39)
        v_41 = self.1_backbone_0_inception_4_bottleneck_0(v_40)
        v_42 = self.1_backbone_0_inception_4_convs_0_0(v_41)
        v_43 = self.1_backbone_0_inception_4_convs_1_0(v_41)
        v_44 = self.1_backbone_0_inception_4_convs_2_0(v_41)
        v_45 = self.1_backbone_0_inception_4_mp_conv_0(v_40)
        v_46 = self.1_backbone_0_inception_4_mp_conv_1_0(v_45)
        v_47 = torch.cat((v_42, v_43, v_44, v_46), dim=1)
        v_48 = self.1_backbone_0_inception_4_norm(v_47)
        v_49 = self.1_backbone_0_inception_4_act(v_48)
        v_50 = self.1_backbone_0_inception_5_bottleneck_0(v_49)
        v_51 = self.1_backbone_0_inception_5_convs_0_0(v_50)
        v_52 = self.1_backbone_0_inception_5_convs_1_0(v_50)
        v_53 = self.1_backbone_0_inception_5_convs_2_0(v_50)
        v_54 = self.1_backbone_0_inception_5_mp_conv_0(v_49)
        v_55 = self.1_backbone_0_inception_5_mp_conv_1_0(v_54)
        v_56 = torch.cat((v_51, v_52, v_53, v_55), dim=1)
        v_57 = self.1_backbone_0_inception_5_norm(v_56)
        v_58 = self.1_backbone_0_shortcut_1(v_31)
        v_59 = (v_57 + v_58)
        v_60 = self.1_backbone_0_act_1(v_59)
        v_61 = self.1_head_0_0_gap(v_60)
        v_62 = v_61.reshape(1, 128)
        v_63 = self.1_head_0_1_0(v_62)
        v_64 = self.2(v_63)
        return v_64

def export_torchscript():
    net = Model()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 1, 1500, dtype=torch.float)

    mod = torch.jit.trace(net, v_0)
    mod.save("../../../../../../../models/traced_model_pnnx.py.pt")

def export_onnx():
    net = Model()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 1, 1500, dtype=torch.float)

    torch.onnx._export(net, v_0, "../../../../../../../models/traced_model_pnnx.py.onnx", export_params=True, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=13, input_names=['in0'], output_names=['out0'])

def test_inference():
    net = Model()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 1, 1500, dtype=torch.float)

    return net(v_0)

if __name__ == "__main__":
    print(test_inference())
